* Introducción

Este es el repositorio con el contenido del curso en *Aprendizaje Estadístico*
ofrecido a estudiantes de semestres avanzados en las licenciaturas de matemáticas aplicadas,
ciencia de datos y actuaría.

* Objetivo

El Aprendizaje Estadístico trata de cómo establecer reglas de asociación al
observar un conjunto de datos. En este curso estudiaremos las ideas
fundamentales detrás de los técnicas de aprendizaje e incorporaremos con
conceptos familiares de estadística. El libro de texto será [[cite:&James2021]] y
lo complementaremos con el enfoque de [[cite:&Kuhn2013]]. Se estudiarán, además,
técnicas estadísticas modernas aplicadas a modelado predictivo por medio de
lecturas que acompañaran el curso.
  

* Temario

El temario para el semestre de primavera 2022 se puede encontrar [[https://github.com/agarbuno/aprendizaje-estadistico/blob/spring-2022/docs/temario.pdf][aqui]]. 

* Recursos

El contenido actual del curso se encuentra en la rama: [[https://github.com/agarbuno/aprendizaje-estadistico/tree/spring-2022][spring-2022]].

* Evaluación

La evaluación del curso será por medio de:
- Participación
- Tareas
- Evaluaciones parciales 
- Proyecto final

La entrega de los trabajos/tareas se realizará por medio de un [[https://github.blog/2021-08-12-teaching-learning-github-classroom-visual-studio-code/][Github Classroom]]. 

bibliographystyle:abbrvnat
bibliography:./references.bib
